# Generated by Django 5.0.6 on 2024-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('1', 'Riesgo I'), ('2', 'Riesgo II'), ('3', 'Riesgo III'), ('4', 'Riesgo IV'), ('5', 'Riesgo V')], help_text='Nivel de riesgo', max_length=100)),
                ('porcentaje_nivel', models.DecimalField(decimal_places=2, help_text='Porcentaje del nivel de riesgo', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveIntegerField()),
                ('prima_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('salud_empleador', 'Salud Empleador'), ('salud_empleado', 'Salud Empleado'), ('pension_empleador', 'Pensión Empleador'), ('pension_empleado', 'Pensión Empleado')], max_length=20)),
                ('porcentaje_seguridad_social', models.DecimalField(decimal_places=2, help_text='Porcentaje de SS', max_digits=5)),
            ],
        ),
    ]
