# Generated by Django 5.0.6 on 2024-06-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], max_length=20)),
                ('fecha_expedicion', models.DateField()),
                ('nro_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('estado_cuenta', models.BooleanField(default=False)),
                ('nombre1', models.CharField(max_length=255)),
                ('nombre2', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('salario_base', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('GESTOR', 'Gestor'), ('OPERADOR', 'Operador'), ('LECTOR', 'Lector')], default='GESTOR', max_length=8)),
                ('tipo_empleado', models.CharField(blank=True, choices=[('INDEPENDIENTE', 'Independiente'), ('DEPENDIENTE', 'Dependiente')], max_length=13, null=True)),
                ('auxilio_transporte', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('0.522%', 'Riesgo I: 0.522%'), ('1.044%', 'Riesgo II: 1.044%'), ('2.436%', 'Riesgo III: 2.436%'), ('4.350%', 'Riesgo IV: 4.350%'), ('6.960%', 'Riesgo V: 6.960%')], help_text='Nivel de riesgo y porcentaje', max_length=20, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.ciudad')),
            ],
        ),
    ]
